//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentFormat.OpenXml.Validation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentFormat.OpenXml.Validation.ValidationResources", typeof(ValidationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception: {0}..
        /// </summary>
        internal static string ExceptionError {
            get {
                return ResourceManager.GetString("ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any element in namespace &apos;{0}&apos;.
        /// </summary>
        internal static string Fmt_AnyElementInNamespace {
            get {
                return ResourceManager.GetString("Fmt_AnyElementInNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}:{1}&gt;.
        /// </summary>
        internal static string Fmt_ElementName {
            get {
                return ResourceManager.GetString("Fmt_ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Fmt_ElementNameSeparator {
            get {
                return ResourceManager.GetString("Fmt_ElementNameSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  List of possible elements expected: {0}..
        /// </summary>
        internal static string Fmt_ListOfPossibleElements {
            get {
                return ResourceManager.GetString("Fmt_ListOfPossibleElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; needs to specify a proper prefix when defined on an AlternateContent element..
        /// </summary>
        internal static string MC_ErrorOnUnprefixedAttributeName {
            get {
                return ResourceManager.GetString("MC_ErrorOnUnprefixedAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ignorable attribute is invalid - The value &apos;{0}&apos; contains an invalid prefix that is not defined..
        /// </summary>
        internal static string MC_InvalidIgnorableAttribute {
            get {
                return ResourceManager.GetString("MC_InvalidIgnorableAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MustUnderstand attribute is invalid - The value &apos;{0}&apos; contains an invalid prefix that is not defined..
        /// </summary>
        internal static string MC_InvalidMustUnderstandAttribute {
            get {
                return ResourceManager.GetString("MC_InvalidMustUnderstandAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PreserveAttributes attribute is invalid - The value &apos;{0}&apos; contains invalid qualified names. The ProcessAttributes attribute value cannot reference any attribute name that does not belong to a namespace that is identified by the Ignorable attribute of the same element..
        /// </summary>
        internal static string MC_InvalidPreserveAttributesAttribute {
            get {
                return ResourceManager.GetString("MC_InvalidPreserveAttributesAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PreserveElements attribute is invalid - The value &apos;{0}&apos; contains invalid qualified names. The PreserveElements attribute value cannot reference any element name that does not belong to a namespace that is identified by the Ignorable attribute of the same element..
        /// </summary>
        internal static string MC_InvalidPreserveElementsAttribute {
            get {
                return ResourceManager.GetString("MC_InvalidPreserveElementsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProcessContent attribute is invalid - The value &apos;{0}&apos; contains invalid qualified names. The ProcessContent attribute value cannot reference any element name that does not belong to a namespace that is identified by the Ignorable attribute of the same element..
        /// </summary>
        internal static string MC_InvalidProcessContentAttribute {
            get {
                return ResourceManager.GetString("MC_InvalidProcessContentAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Requires attribute is invalid - The value &apos;{0}&apos; contains an invalid prefix that is not defined..
        /// </summary>
        internal static string MC_InvalidRequiresAttribute {
            get {
                return ResourceManager.GetString("MC_InvalidRequiresAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} element should not have an xml:lang or xml:space attribute..
        /// </summary>
        internal static string MC_InvalidXmlAttribute {
            get {
                return ResourceManager.GetString("MC_InvalidXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element should not have an xml:lang or xml:space attribute and also be identified by a ProcessContent attribute..
        /// </summary>
        internal static string MC_InvalidXmlAttributeWithProcessContent {
            get {
                return ResourceManager.GetString("MC_InvalidXmlAttributeWithProcessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Choice elements must have a Requires attribute whose value contains a whitespace delimited list of namespace prefixes..
        /// </summary>
        internal static string MC_MissedRequiresAttribute {
            get {
                return ResourceManager.GetString("MC_MissedRequiresAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An AlternateContent element must contain one or more Choice child elements, optionally followed by a Fallback child element..
        /// </summary>
        internal static string MC_ShallContainChoice {
            get {
                return ResourceManager.GetString("MC_ShallContainChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An AlternateContent element cannot be the child of an AlternateContent element..
        /// </summary>
        internal static string MC_ShallNotContainAlternateContent {
            get {
                return ResourceManager.GetString("MC_ShallNotContainAlternateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package/part &apos;{0}&apos; cannot have a relationship that targets &apos;{1}&apos;..
        /// </summary>
        internal static string Pkg_DataPartReferenceIsNotAllowed {
            get {
                return ResourceManager.GetString("Pkg_DataPartReferenceIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ExtendedPart &apos;{0}&apos; was encountered with a relationship type that starts with &quot;http://schemas.openxmlformats.org&quot;. Expected a defined part instead based on the relationship type..
        /// </summary>
        internal static string Pkg_ExtendedPartIsOpenXmlPart {
            get {
                return ResourceManager.GetString("Pkg_ExtendedPartIsOpenXmlPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package/part &apos;{0}&apos; can only have one instance of relationship that targets part &apos;{1}&apos;..
        /// </summary>
        internal static string Pkg_OnlyOnePartAllowed {
            get {
                return ResourceManager.GetString("Pkg_OnlyOnePartAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package/part &apos;{0}&apos; cannot have a relationship that targets part &apos;{1}&apos;..
        /// </summary>
        internal static string Pkg_PartIsNotAllowed {
            get {
                return ResourceManager.GetString("Pkg_PartIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required part &apos;{0}&apos; is missing..
        /// </summary>
        internal static string Pkg_RequiredPartDoNotExist {
            get {
                return ResourceManager.GetString("Pkg_RequiredPartDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; cannot appear more than once if content model type is &quot;all&quot;..
        /// </summary>
        internal static string Sch_AllElement {
            get {
                return ResourceManager.GetString("Sch_AllElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; attribute is invalid - The value &apos;{1}&apos; is not valid according to any of the memberTypes of the union..
        /// </summary>
        internal static string Sch_AttributeUnionFailedEx {
            get {
                return ResourceManager.GetString("Sch_AttributeUnionFailedEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; has invalid value &apos;{1}&apos;.{2}.
        /// </summary>
        internal static string Sch_AttributeValueDataTypeDetailed {
            get {
                return ResourceManager.GetString("Sch_AttributeValueDataTypeDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; element is invalid - The value &apos;{1}&apos; is not valid according to any of the memberTypes of the union..
        /// </summary>
        internal static string Sch_ElementUnionFailedEx {
            get {
                return ResourceManager.GetString("Sch_ElementUnionFailedEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; has invalid value &apos;{1}&apos;.{2}.
        /// </summary>
        internal static string Sch_ElementValueDataTypeDetailed {
            get {
                return ResourceManager.GetString("Sch_ElementValueDataTypeDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The attribute value cannot be empty..
        /// </summary>
        internal static string Sch_EmptyAttributeValue {
            get {
                return ResourceManager.GetString("Sch_EmptyAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The text value cannot be empty..
        /// </summary>
        internal static string Sch_EmptyElementValue {
            get {
                return ResourceManager.GetString("Sch_EmptyElementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The Enumeration constraint failed..
        /// </summary>
        internal static string Sch_EnumerationConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_EnumerationConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element has incomplete content.{0}.
        /// </summary>
        internal static string Sch_IncompleteContentExpectingComplex {
            get {
                return ResourceManager.GetString("Sch_IncompleteContentExpectingComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; is a leaf element and cannot contain children..
        /// </summary>
        internal static string Sch_InvalidChildinLeafElement {
            get {
                return ResourceManager.GetString("Sch_InvalidChildinLeafElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element has invalid child element &apos;{0}&apos;.{1}.
        /// </summary>
        internal static string Sch_InvalidElementContentExpectingComplex {
            get {
                return ResourceManager.GetString("Sch_InvalidElementContentExpectingComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element has child element &apos;{0}&apos; of invalid type &apos;{1}&apos;..
        /// </summary>
        internal static string Sch_InvalidElementContentWrongType {
            get {
                return ResourceManager.GetString("Sch_InvalidElementContentWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The actual length according to data type &apos;{0}&apos; is not equal to the specified length. The expected length is {1}..
        /// </summary>
        internal static string Sch_LengthConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_LengthConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The MaxExclusive constraint failed. The value must be less than {0}..
        /// </summary>
        internal static string Sch_MaxExclusiveConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_MaxExclusiveConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The MaxInclusive constraint failed. The value must be less than or equal to {0}..
        /// </summary>
        internal static string Sch_MaxInclusiveConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_MaxInclusiveConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The actual length according to data type &apos;{0}&apos; is greater than the MaxLength value. The length must be smaller than or equal to {1}..
        /// </summary>
        internal static string Sch_MaxLengthConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_MaxLengthConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The MinExclusive constraint failed. The value must be greater than {0}..
        /// </summary>
        internal static string Sch_MinExclusiveConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_MinExclusiveConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The MinInclusive constraint failed. The value must be greater than or equal to {0}..
        /// </summary>
        internal static string Sch_MinInclusiveConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_MinInclusiveConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The actual length according to data type &apos;{0}&apos; is less than the MinLength value. The length must be bigger than or equal to {1}..
        /// </summary>
        internal static string Sch_MinLengthConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_MinLengthConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required attribute &apos;{0}&apos; is missing..
        /// </summary>
        internal static string Sch_MissRequiredAttribute {
            get {
                return ResourceManager.GetString("Sch_MissRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The Pattern constraint failed. The expected pattern is {0}..
        /// </summary>
        internal static string Sch_PatternConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_PatternConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The string &apos;{0}&apos; is not a valid &apos;{1}&apos; value..
        /// </summary>
        internal static string Sch_StringIsNotValidValue {
            get {
                return ResourceManager.GetString("Sch_StringIsNotValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The TotalDigits constraint failed. The expected number of digits is {0}..
        /// </summary>
        internal static string Sch_TotalDigitsConstraintFailed {
            get {
                return ResourceManager.GetString("Sch_TotalDigitsConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; attribute is not declared..
        /// </summary>
        internal static string Sch_UndeclaredAttribute {
            get {
                return ResourceManager.GetString("Sch_UndeclaredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element has unexpected child element &apos;{0}&apos;.{1}.
        /// </summary>
        internal static string Sch_UnexpectedElementContentExpectingComplex {
            get {
                return ResourceManager.GetString("Sch_UnexpectedElementContentExpectingComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; should be absent when the value of attribute &apos;{1}&apos; is not {2}..
        /// </summary>
        internal static string Sem_AttributeAbsentConditionToNonValue {
            get {
                return ResourceManager.GetString("Sem_AttributeAbsentConditionToNonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; should be absent when the value of attribute &apos;{1}&apos; is {2}..
        /// </summary>
        internal static string Sem_AttributeAbsentConditionToValue {
            get {
                return ResourceManager.GetString("Sem_AttributeAbsentConditionToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; and &apos;{1}&apos; cannot be present at the same time. Only one of these attributes &apos;{2}&apos; can be present at a given time..
        /// </summary>
        internal static string Sem_AttributeMutualExclusive {
            get {
                return ResourceManager.GetString("Sem_AttributeMutualExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; should be present when the value of attribute &apos;{1}&apos; is {2}..
        /// </summary>
        internal static string Sem_AttributeRequiredConditionToValue {
            get {
                return ResourceManager.GetString("Sem_AttributeRequiredConditionToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; should have value(s) {1} when attribute &apos;{2}&apos; has value(s) {3}. Current value of attribute &apos;{4}&apos; is &apos;{5}&apos;..
        /// </summary>
        internal static string Sem_AttributeValueConditionToAnother {
            get {
                return ResourceManager.GetString("Sem_AttributeValueConditionToAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; has invalid value &apos;{1}&apos;.{2}.
        /// </summary>
        internal static string Sem_AttributeValueDataTypeDetailed {
            get {
                return ResourceManager.GetString("Sem_AttributeValueDataTypeDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; has value &apos;{1}&apos;. It should be less than or equal to the value of attribute &apos;{2}&apos; which is &apos;{3}&apos;..
        /// </summary>
        internal static string Sem_AttributeValueLessEqualToAnother {
            get {
                return ResourceManager.GetString("Sem_AttributeValueLessEqualToAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; has value &apos;{1}&apos;. It should be less than the value of attribute &apos;{2}&apos; which is &apos;{3}&apos;..
        /// </summary>
        internal static string Sem_AttributeValueLessEqualToAnotherEx {
            get {
                return ResourceManager.GetString("Sem_AttributeValueLessEqualToAnotherEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; should have unique value in the whole document. Its current value &apos;{1}&apos; duplicates with others..
        /// </summary>
        internal static string Sem_AttributeValueUniqueInDocument {
            get {
                return ResourceManager.GetString("Sem_AttributeValueUniqueInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship &apos;{0}&apos; referenced by attribute &apos;{1}&apos; has incorrect type. Its type should be &apos;{2}&apos;..
        /// </summary>
        internal static string Sem_IncorrectRelationshipType {
            get {
                return ResourceManager.GetString("Sem_IncorrectRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relationship &apos;{0}&apos; referenced by attribute &apos;{1}&apos; does not exist..
        /// </summary>
        internal static string Sem_InvalidRelationshipId {
            get {
                return ResourceManager.GetString("Sem_InvalidRelationshipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The actual length is greater than the MaxLength value. The length must be smaller than or equal to {0}..
        /// </summary>
        internal static string Sem_MaxLengthConstraintFailed {
            get {
                return ResourceManager.GetString("Sem_MaxLengthConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The actual length is less than the MinLength value. The length must be bigger than or equal to {0}..
        /// </summary>
        internal static string Sem_MinLengthConstraintFailed {
            get {
                return ResourceManager.GetString("Sem_MinLengthConstraintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; referenced by &apos;{1}@{2}&apos; does not exist in part &apos;{3}&apos;. The index is &apos;{4}&apos;..
        /// </summary>
        internal static string Sem_MissingIndexedElement {
            get {
                return ResourceManager.GetString("Sem_MissingIndexedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; referenced by &apos;{1}@{2}&apos; does not exist in part &apos;{3}&apos;. The reference value is &apos;{4}&apos;..
        /// </summary>
        internal static string Sem_MissingReferenceElement {
            get {
                return ResourceManager.GetString("Sem_MissingReferenceElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; should have unique value. Its current value &apos;{1}&apos; duplicates with others..
        /// </summary>
        internal static string Sem_UniqueAttributeValue {
            get {
                return ResourceManager.GetString("Sem_UniqueAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:base64Binary.
        /// </summary>
        internal static string TypeName_base64Binary {
            get {
                return ResourceManager.GetString("TypeName_base64Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:hexBinary.
        /// </summary>
        internal static string TypeName_hexBinary {
            get {
                return ResourceManager.GetString("TypeName_hexBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:ID.
        /// </summary>
        internal static string TypeName_ID {
            get {
                return ResourceManager.GetString("TypeName_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:integer.
        /// </summary>
        internal static string TypeName_Integer {
            get {
                return ResourceManager.GetString("TypeName_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:language.
        /// </summary>
        internal static string TypeName_language {
            get {
                return ResourceManager.GetString("TypeName_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:NCName.
        /// </summary>
        internal static string TypeName_NCName {
            get {
                return ResourceManager.GetString("TypeName_NCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:nonNegativeInteger.
        /// </summary>
        internal static string TypeName_nonNegativeInteger {
            get {
                return ResourceManager.GetString("TypeName_nonNegativeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:positiveInteger.
        /// </summary>
        internal static string TypeName_positiveInteger {
            get {
                return ResourceManager.GetString("TypeName_positiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:QName.
        /// </summary>
        internal static string TypeName_QName {
            get {
                return ResourceManager.GetString("TypeName_QName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema:token.
        /// </summary>
        internal static string TypeName_token {
            get {
                return ResourceManager.GetString("TypeName_token", resourceCulture);
            }
        }
    }
}
