# Copyright (c) Microsoft Open Technologies, Inc.  All rights reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

# Common configuration for makefile

# Misc

O=obj

# Compiler

MSBUILD=msbuild.exe

# CSharp Compiler

CSC=csc.exe
CSCFLAGS=/nologo /warn:4

!IFDEF VDEBUG

CSCFLAGS=$(CSCFLAGS) /debug /checked /define:DEBUG;TRACE

!ELSE

CSCFLAGS=$(CSCFLAGS) /debug:pdbonly /o

!ENDIF #VDEBUG

# IDL Compiler

# Resource compiler flags

RESGEN=resgen.exe
RC=rc
RCFLAGS=/usesourcepath

# Source dirs

OXAPIDIR=.
SRCDIR=$(OXAPIDIR)\src
TOOLSRCDIR=$(OXAPIDIR)\toolsrc
APIGENDIR=$(SRCDIR)\ApiGen
DOMGENDIR=$(SRCDIR)\DomGenV3
OXFRAMEWORKDIR=$(SRCDIR)\Framework
OFAPIDIR=$(SRCDIR)\ofapi
GENERATEDCODEDIR=$(SRCDIR)\GeneratedCode
OFAPI4SDBBUILDERDIR=$(TOOLSRCDIR)\Ofapi4SdbBuilder
SCHEMAPROCESSORDIR=$(TOOLSRCDIR)\SchemaProcessor
SDBBUILDERDIR=$(TOOLSRCDIR)\SdbBuilder
SEMANTICCONSTRAINTREGGENDIR=$(TOOLSRCDIR)\SemanticConstraintRegGen
SCHEMATRONGENDIR=$(TOOLSRCDIR)\SchematronGen

# Build dirs

BUILDDIR=$(OXAPIDIR)\build
APIGENBLDDIR=$(BUILDDIR)\ApiGen
DOMGENBLDDIR=$(BUILDDIR)\DomGenV3
FRAMEWORKBLDDIR=$(BUILDDIR)\Framework
OFAPIBLDDIR=$(BUILDDIR)\OpenXmlSdkLib
GENERATEDCODEBLDDIR=$(BUILDDIR)\GeneratedCode
OFAPI4SDBBUILDERBLDDIR=$(BUILDDIR)\Ofapi4SdbBuilder
SCHEMAPROCESSORBLDDIR=$(BUILDDIR)\SchemaProcessor
SDBBUILDERBLDDIR=$(BUILDDIR)\SdbBuilder
SEMANTICCONSTRAINTREGGENBLDDIR=$(BUILDDIR)\SemanticConstraintRegGen
SCHEMATRONGENBLDDIR=$(BUILDDIR)\SchematronGen

