// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace DocumentFormat.OpenXml.Features
{
    /// <summary>
    /// Options to declare how paragraph ids should be generated.
    /// </summary>
    public class ParagraphIdOptions
    {
        /// <summary>
        /// Gets a value indicating whether or not paragraph ids should be autogenerated on elements.
        /// </summary>
        public bool AutoGenerateIds { get; init; } = true;

        /// <summary>
        /// Gets a value indicating whether or not uniqueness should be guaranteed on elements added to the document. This will change a node's para id if it has already been registered.
        /// </summary>
        public bool EnsureUniquenessOnExistingNodes { get; init; } = true;
    }
}
