//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.IO.Packaging.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.IO.Packaging.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format error in package..
        /// </summary>
        internal static string BadPackageFormat {
            get {
                return ResourceManager.GetString("BadPackageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify readonly container..
        /// </summary>
        internal static string CannotModifyReadOnlyContainer {
            get {
                return ResourceManager.GetString("CannotModifyReadOnlyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve parts of writeonly container..
        /// </summary>
        internal static string CannotRetrievePartsOfWriteOnlyContainer {
            get {
                return ResourceManager.GetString("CannotRetrievePartsOfWriteOnlyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileMode/FileAccess for Part.GetStream is not compatible with FileMode/FileAccess used to open the Package..
        /// </summary>
        internal static string ContainerAndPartModeIncompatible {
            get {
                return ResourceManager.GetString("ContainerAndPartModeIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentType string cannot have leading/trailing Linear White Spaces [LWS - RFC 2616]..
        /// </summary>
        internal static string ContentTypeCannotHaveLeadingTrailingLWS {
            get {
                return ResourceManager.GetString("ContentTypeCannotHaveLeadingTrailingLWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized root element in Core Properties part..
        /// </summary>
        internal static string CorePropertiesElementExpected {
            get {
                return ResourceManager.GetString("CorePropertiesElementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNew not supported..
        /// </summary>
        internal static string CreateNewNotSupported {
            get {
                return ResourceManager.GetString("CreateNewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target of the Core Properties relationship does not reference an existing part..
        /// </summary>
        internal static string DanglingMetadataRelationship {
            get {
                return ResourceManager.GetString("DanglingMetadataRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default tag is not valid per the schema. Verify that attributes are correct..
        /// </summary>
        internal static string DefaultTagDoesNotMatchSchema {
            get {
                return ResourceManager.GetString("DefaultTagDoesNotMatchSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one &apos;{0}&apos; property found..
        /// </summary>
        internal static string DuplicateCorePropertyName {
            get {
                return ResourceManager.GetString("DuplicateCorePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; element must be empty..
        /// </summary>
        internal static string ElementIsNotEmptyElement {
            get {
                return ResourceManager.GetString("ElementIsNotEmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding format is not supported. Only UTF-8 and UTF-16 are supported..
        /// </summary>
        internal static string EncodingNotSupported {
            get {
                return ResourceManager.GetString("EncodingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships tag expected at root level..
        /// </summary>
        internal static string ExpectedRelationshipsElementTag {
            get {
                return ResourceManager.GetString("ExpectedRelationshipsElementTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;;&apos; must be followed by parameter=value pair..
        /// </summary>
        internal static string ExpectingParameterValuePairs {
            get {
                return ResourceManager.GetString("ExpectingParameterValuePairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon separator is required between two valid parameter=value pairs..
        /// </summary>
        internal static string ExpectingSemicolon {
            get {
                return ResourceManager.GetString("ExpectingSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format..
        /// </summary>
        internal static string FileFormatException {
            get {
                return ResourceManager.GetString("FileFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format..
        /// </summary>
        internal static string FileFormatExceptionWithFileName {
            get {
                return ResourceManager.GetString("FileFormatExceptionWithFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;fragment&apos; parameter must start with a number sign..
        /// </summary>
        internal static string FragmentMustStartWithHash {
            get {
                return ResourceManager.GetString("FragmentMustStartWithHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackagePart subclass must implement GetContentTypeCore method if passing a null value for the content type when PackagePart object is constructed..
        /// </summary>
        internal static string GetContentTypeCoreNotImplemented {
            get {
                return ResourceManager.GetString("GetContentTypeCoreNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open package because FileMode or FileAccess value is not valid for the stream..
        /// </summary>
        internal static string IncompatibleModeOrAccess {
            get {
                return ResourceManager.GetString("IncompatibleModeOrAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package URI obtained from the pack URI cannot contain a Fragment..
        /// </summary>
        internal static string InnerPackageUriHasFragment {
            get {
                return ResourceManager.GetString("InnerPackageUriHasFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Linear White Space character is not valid..
        /// </summary>
        internal static string InvalidLinearWhiteSpaceCharacter {
            get {
                return ResourceManager.GetString("InvalidLinearWhiteSpaceCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value must be a valid token or a quoted string as per RFC 2616..
        /// </summary>
        internal static string InvalidParameterValue {
            get {
                return ResourceManager.GetString("InvalidParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter and value pair is not valid. Expected form is parameter=value..
        /// </summary>
        internal static string InvalidParameterValuePair {
            get {
                return ResourceManager.GetString("InvalidParameterValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part URI is not valid per rules defined in the Open Packaging Conventions specification..
        /// </summary>
        internal static string InvalidPartUri {
            get {
                return ResourceManager.GetString("InvalidPartUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; property name is not valid in Core Properties part..
        /// </summary>
        internal static string InvalidPropertyNameInCorePropertiesPart {
            get {
                return ResourceManager.GetString("InvalidPropertyNameInCorePropertiesPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type cannot contain only spaces or be empty..
        /// </summary>
        internal static string InvalidRelationshipType {
            get {
                return ResourceManager.GetString("InvalidRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A token is not valid. Refer to RFC 2616 for correct grammar of content types..
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentType string is not valid. Expected format is type/subtype..
        /// </summary>
        internal static string InvalidTypeSubType {
            get {
                return ResourceManager.GetString("InvalidTypeSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; attribute value is not valid..
        /// </summary>
        internal static string InvalidValueForTheAttribute {
            get {
                return ResourceManager.GetString("InvalidValueForTheAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships XML elements cannot specify attribute &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidXmlBaseAttributePresent {
            get {
                return ResourceManager.GetString("InvalidXmlBaseAttributePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecoverable system error..
        /// </summary>
        internal static string InvariantFailure {
            get {
                return ResourceManager.GetString("InvariantFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package has more than one Core Properties relationship..
        /// </summary>
        internal static string MoreThanOneMetadataRelationships {
            get {
                return ResourceManager.GetString("MoreThanOneMetadataRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetMode for a Core Properties relationship must be &apos;Internal&apos;..
        /// </summary>
        internal static string NoExternalTargetForMetadataRelationship {
            get {
                return ResourceManager.GetString("NoExternalTargetForMetadataRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Properties part: core property elements can contain only text data..
        /// </summary>
        internal static string NoStructuredContentInsideProperties {
            get {
                return ResourceManager.GetString("NoStructuredContentInsideProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ID conflicts with the ID of an existing relationship for the specified source..
        /// </summary>
        internal static string NotAUniqueRelationshipId {
            get {
                return ResourceManager.GetString("NotAUniqueRelationshipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRelationship part URI syntax is not valid..
        /// </summary>
        internal static string NotAValidRelationshipPartUri {
            get {
                return ResourceManager.GetString("NotAValidRelationshipPartUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ID is not a valid XSD ID..
        /// </summary>
        internal static string NotAValidXmlIdString {
            get {
                return ResourceManager.GetString("NotAValidXmlIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetContentTypeCore method cannot return null for the content type stream..
        /// </summary>
        internal static string NullContentTypeProvided {
            get {
                return ResourceManager.GetString("NullContentTypeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned stream for the part is null..
        /// </summary>
        internal static string NullStreamReturned {
            get {
                return ResourceManager.GetString("NullStreamReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package object was closed and disposed, so cannot carry out operations on this object or any stream opened on a part of this package..
        /// </summary>
        internal static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset must be greater than or equal to zero..
        /// </summary>
        internal static string OffsetNegative {
            get {
                return ResourceManager.GetString("OffsetNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override tag is not valid per the schema. Verify that attributes are correct..
        /// </summary>
        internal static string OverrideTagDoesNotMatchSchema {
            get {
                return ResourceManager.GetString("OverrideTagDoesNotMatchSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part was deleted..
        /// </summary>
        internal static string PackagePartDeleted {
            get {
                return ResourceManager.GetString("PackagePartDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRelationship with specified ID does not exist for the source part..
        /// </summary>
        internal static string PackagePartRelationshipDoesNotExist {
            get {
                return ResourceManager.GetString("PackagePartRelationshipDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRelationship with specified ID does not exist at the Package level..
        /// </summary>
        internal static string PackageRelationshipDoesNotExist {
            get {
                return ResourceManager.GetString("PackageRelationshipDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access part because parent package was closed..
        /// </summary>
        internal static string ParentContainerClosed {
            get {
                return ResourceManager.GetString("ParentContainerClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add part for the specified URI because it is already in the package..
        /// </summary>
        internal static string PartAlreadyExists {
            get {
                return ResourceManager.GetString("PartAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part corresponding to URI &apos;{0}&apos; does not exist in package..
        /// </summary>
        internal static string PartDoesNotExist {
            get {
                return ResourceManager.GetString("PartDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add part to the package. Part names cannot be derived from another part name by appending segments to it..
        /// </summary>
        internal static string PartNamePrefixExists {
            get {
                return ResourceManager.GetString("PartNamePrefixExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part URI cannot contain a Fragment component..
        /// </summary>
        internal static string PartUriCannotHaveAFragment {
            get {
                return ResourceManager.GetString("PartUriCannotHaveAFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part URI is empty..
        /// </summary>
        internal static string PartUriIsEmpty {
            get {
                return ResourceManager.GetString("PartUriIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part URI cannot end with a forward slash..
        /// </summary>
        internal static string PartUriShouldNotEndWithForwardSlash {
            get {
                return ResourceManager.GetString("PartUriShouldNotEndWithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part URI cannot start with two forward slashes..
        /// </summary>
        internal static string PartUriShouldNotStartWithTwoForwardSlashes {
            get {
                return ResourceManager.GetString("PartUriShouldNotStartWithTwoForwardSlashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part URI must start with a forward slash..
        /// </summary>
        internal static string PartUriShouldStartWithForwardSlash {
            get {
                return ResourceManager.GetString("PartUriShouldStartWithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Properties part: A property start-tag was expected..
        /// </summary>
        internal static string PropertyStartTagExpected {
            get {
                return ResourceManager.GetString("PropertyStartTagExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected number of attributes is found on &apos;{0}&apos;..
        /// </summary>
        internal static string PropertyWrongNumbOfAttribsDefinedOn {
            get {
                return ResourceManager.GetString("PropertyWrongNumbOfAttribsDefinedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer too small to hold results of Read..
        /// </summary>
        internal static string ReadBufferTooSmall {
            get {
                return ResourceManager.GetString("ReadBufferTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of bytes to read cannot be negative..
        /// </summary>
        internal static string ReadCountNegative {
            get {
                return ResourceManager.GetString("ReadCountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        internal static string ReadNotSupported {
            get {
                return ResourceManager.GetString("ReadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to read-only stream..
        /// </summary>
        internal static string ReadOnlyStream {
            get {
                return ResourceManager.GetString("ReadOnlyStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect content type for PackageRelationship part..
        /// </summary>
        internal static string RelationshipPartIncorrectContentType {
            get {
                return ResourceManager.GetString("RelationshipPartIncorrectContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRelationship parts cannot have relationships to other parts..
        /// </summary>
        internal static string RelationshipPartsCannotHaveRelationships {
            get {
                return ResourceManager.GetString("RelationshipPartsCannotHaveRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRelationship part URI is expected..
        /// </summary>
        internal static string RelationshipPartUriExpected {
            get {
                return ResourceManager.GetString("RelationshipPartUriExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRelationship part URI is not expected..
        /// </summary>
        internal static string RelationshipPartUriNotExpected {
            get {
                return ResourceManager.GetString("RelationshipPartUriNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships tag has extra attributes..
        /// </summary>
        internal static string RelationshipsTagHasExtraAttributes {
            get {
                return ResourceManager.GetString("RelationshipsTagHasExtraAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship tag contains incorrect attribute..
        /// </summary>
        internal static string RelationshipTagDoesntMatchSchema {
            get {
                return ResourceManager.GetString("RelationshipTagDoesntMatchSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRelationship target must be relative URI if TargetMode is Internal..
        /// </summary>
        internal static string RelationshipTargetMustBeRelative {
            get {
                return ResourceManager.GetString("RelationshipTargetMustBeRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageRelationship cannot target another PackageRelationship..
        /// </summary>
        internal static string RelationshipToRelationshipIllegal {
            get {
                return ResourceManager.GetString("RelationshipToRelationshipIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; tag requires a nonempty &apos;{1}&apos; attribute..
        /// </summary>
        internal static string RequiredAttributeEmpty {
            get {
                return ResourceManager.GetString("RequiredAttributeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; tag requires attribute &apos;{1}&apos;..
        /// </summary>
        internal static string RequiredAttributeMissing {
            get {
                return ResourceManager.GetString("RequiredAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship tag requires attribute &apos;{0}&apos;..
        /// </summary>
        internal static string RequiredRelationshipAttributeMissing {
            get {
                return ResourceManager.GetString("RequiredRelationshipAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access Stream object because it was closed or disposed..
        /// </summary>
        internal static string StreamObjectDisposed {
            get {
                return ResourceManager.GetString("StreamObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncate not supported..
        /// </summary>
        internal static string TruncateNotSupported {
            get {
                return ResourceManager.GetString("TruncateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Types tag not found..
        /// </summary>
        internal static string TypesElementExpected {
            get {
                return ResourceManager.GetString("TypesElementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types tag has attributes not valid per the schema..
        /// </summary>
        internal static string TypesTagHasExtraAttributes {
            get {
                return ResourceManager.GetString("TypesTagHasExtraAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Types XML does not match schema..
        /// </summary>
        internal static string TypesXmlDoesNotMatchSchema {
            get {
                return ResourceManager.GetString("TypesXmlDoesNotMatchSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown xsi:type for DateTime on &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownDCDateTimeXsiType {
            get {
                return ResourceManager.GetString("UnknownDCDateTimeXsiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized namespace in Core Properties part..
        /// </summary>
        internal static string UnknownNamespaceInCorePropertiesPart {
            get {
                return ResourceManager.GetString("UnknownNamespaceInCorePropertiesPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized tag found in Relationships XML..
        /// </summary>
        internal static string UnknownTagEncountered {
            get {
                return ResourceManager.GetString("UnknownTagEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get stream with FileMode.Create, FileMode.CreateNew, FileMode.Truncate, FileMode.Append when access is FileAccess.Read..
        /// </summary>
        internal static string UnsupportedCombinationOfModeAccess {
            get {
                return ResourceManager.GetString("UnsupportedCombinationOfModeAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have absolute URI..
        /// </summary>
        internal static string UriShouldBeAbsolute {
            get {
                return ResourceManager.GetString("UriShouldBeAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI must contain pack:// scheme..
        /// </summary>
        internal static string UriShouldBePackScheme {
            get {
                return ResourceManager.GetString("UriShouldBePackScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be an absolute URI..
        /// </summary>
        internal static string URIShouldNotBeAbsolute {
            get {
                return ResourceManager.GetString("URIShouldNotBeAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer of bytes to be written is too small..
        /// </summary>
        internal static string WriteBufferTooSmall {
            get {
                return ResourceManager.GetString("WriteBufferTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of bytes to write cannot be negative..
        /// </summary>
        internal static string WriteCountNegative {
            get {
                return ResourceManager.GetString("WriteCountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        internal static string WriteNotSupported {
            get {
                return ResourceManager.GetString("WriteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from write-only stream..
        /// </summary>
        internal static string WriteOnlyStream {
            get {
                return ResourceManager.GetString("WriteOnlyStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Core Properties relationship references a part that has an incorrect content type..
        /// </summary>
        internal static string WrongContentTypeForPropertyPart {
            get {
                return ResourceManager.GetString("WrongContentTypeForPropertyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice cannot follow a Fallback..
        /// </summary>
        internal static string XCRChoiceAfterFallback {
            get {
                return ResourceManager.GetString("XCRChoiceAfterFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternateContent must contain one or more Choice elements..
        /// </summary>
        internal static string XCRChoiceNotFound {
            get {
                return ResourceManager.GetString("XCRChoiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice is valid only in AlternateContent..
        /// </summary>
        internal static string XCRChoiceOnlyInAC {
            get {
                return ResourceManager.GetString("XCRChoiceOnlyInAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a cycle of XML compatibility definitions, such that namespace &apos;{0}&apos; overrides itself. This could be due to inconsistent XmlnsCompatibilityAttributes in different assemblies. Please change the definitions to eliminate this cycle..
        /// </summary>
        internal static string XCRCompatCycle {
            get {
                return ResourceManager.GetString("XCRCompatCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Preserve declaration for element {1} in namespace &apos;{0}&apos;..
        /// </summary>
        internal static string XCRDuplicatePreserve {
            get {
                return ResourceManager.GetString("XCRDuplicatePreserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ProcessContent declaration for element &apos;{1}&apos; in namespace &apos;{0}&apos;..
        /// </summary>
        internal static string XCRDuplicateProcessContent {
            get {
                return ResourceManager.GetString("XCRDuplicateProcessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate wildcard Preserve declaration for namespace &apos;{0}&apos;..
        /// </summary>
        internal static string XCRDuplicateWildcardPreserve {
            get {
                return ResourceManager.GetString("XCRDuplicateWildcardPreserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate wildcard ProcessContent declaration for namespace &apos;{0}&apos;..
        /// </summary>
        internal static string XCRDuplicateWildcardProcessContent {
            get {
                return ResourceManager.GetString("XCRDuplicateWildcardProcessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback is valid only in AlternateContent..
        /// </summary>
        internal static string XCRFallbackOnlyInAC {
            get {
                return ResourceManager.GetString("XCRFallbackOnlyInAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; element is not a valid child of AlternateContent. Only Choice and Fallback elements are valid children of an AlternateContent element..
        /// </summary>
        internal static string XCRInvalidACChild {
            get {
                return ResourceManager.GetString("XCRInvalidACChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; attribute is not valid for &apos;{1}&apos; element..
        /// </summary>
        internal static string XCRInvalidAttribInElement {
            get {
                return ResourceManager.GetString("XCRInvalidAttribInElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; format is not valid..
        /// </summary>
        internal static string XCRInvalidFormat {
            get {
                return ResourceManager.GetString("XCRInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have both a specific and a wildcard Preserve declaration for namespace &apos;{0}&apos;..
        /// </summary>
        internal static string XCRInvalidPreserve {
            get {
                return ResourceManager.GetString("XCRInvalidPreserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have both a specific and a wildcard ProcessContent declaration for namespace &apos;{0}&apos;..
        /// </summary>
        internal static string XCRInvalidProcessContent {
            get {
                return ResourceManager.GetString("XCRInvalidProcessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires attribute must contain a valid namespace prefix..
        /// </summary>
        internal static string XCRInvalidRequiresAttribute {
            get {
                return ResourceManager.GetString("XCRInvalidRequiresAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; attribute value is not a valid XML name..
        /// </summary>
        internal static string XCRInvalidXMLName {
            get {
                return ResourceManager.GetString("XCRInvalidXMLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternateContent must contain only one Fallback element..
        /// </summary>
        internal static string XCRMultipleFallbackFound {
            get {
                return ResourceManager.GetString("XCRMultipleFallbackFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MustUnderstand condition failed on namespace &apos;{0}&apos;..
        /// </summary>
        internal static string XCRMustUnderstandFailed {
            get {
                return ResourceManager.GetString("XCRMustUnderstandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; namespace cannot preserve items; it must be declared Ignorable first..
        /// </summary>
        internal static string XCRNSPreserveNotIgnorable {
            get {
                return ResourceManager.GetString("XCRNSPreserveNotIgnorable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; namespace cannot process content; it must be declared Ignorable first..
        /// </summary>
        internal static string XCRNSProcessContentNotIgnorable {
            get {
                return ResourceManager.GetString("XCRNSProcessContentNotIgnorable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice must contain Requires attribute..
        /// </summary>
        internal static string XCRRequiresAttribNotFound {
            get {
                return ResourceManager.GetString("XCRRequiresAttribNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; prefix is not defined..
        /// </summary>
        internal static string XCRUndefinedPrefix {
            get {
                return ResourceManager.GetString("XCRUndefinedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized compatibility attribute &apos;{0}&apos;..
        /// </summary>
        internal static string XCRUnknownCompatAttrib {
            get {
                return ResourceManager.GetString("XCRUnknownCompatAttrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Compatibility element &apos;{0}&apos;..
        /// </summary>
        internal static string XCRUnknownCompatElement {
            get {
                return ResourceManager.GetString("XCRUnknownCompatElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Properties part: Text data of XSD type &apos;DateTime&apos; was expected..
        /// </summary>
        internal static string XsdDateTimeExpected {
            get {
                return ResourceManager.GetString("XsdDateTimeExpected", resourceCulture);
            }
        }
    }
}
