name: Deploy
 
on:
  release: 
    types: [published]
  
jobs: 
  deploy:
    environment: nuget
    runs-on: ubuntu-latest
    needs: [ sign ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Signed
          path: "${github.workspace}/signed"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3

      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${github.workspace}/signed" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
